name: mpaper_10_21_py310
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - nvidia
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _libavif_api=1.3.0
  - _openmp_mutex=4.5
  - aom=3.9.1
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - contourpy=1.3.2
  - cycler=0.12.1
  - dav1d=1.2.1
  - double-conversion=3.3.1
  - ffmpeg=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freeglut=3.2.2
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - graphite2=1.3.14
  - harfbuzz=12.1.0
  - hdf5=1.14.6
  - icu=75.1
  - imath=3.2.1
  - jasper=4.2.8
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libasprintf=0.22.5
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libclang13=21.1.4
  - libcurl=8.16.0
  - libdeflate=1.24
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgettextpo=0.22.5
  - libglib=2.86.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libogg=1.3.5
  - libopencv=4.12.0
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libusb=1.0.29
  - libvorbis=1.3.7
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.4
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - mkl=2024.2.2
  - munkres=1.0.7
  - opencl-headers=2025.06.13
  - opencv=4.12.0
  - openexr=3.3.5
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.3
  - pango=1.56.4
  - patsy=1.0.2
  - pcre2=10.46
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pugixml=1.15
  - py-opencv=4.12.0
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.9.3
  - rav1e=0.7.1
  - sdl2=2.32.56
  - sdl3=3.2.24
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - statsmodels=0.14.5
  - svt-av1=3.1.2
  - tbb=2021.13.0
  - tk=8.6.13
  - tornado=6.5.2
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=16.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
  - pip:
      - anyio==4.11.0
      - certifi==2025.10.5
      - click==8.3.0
      - colorama==0.4.6
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.0.1
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.25.0
      - pyyaml==6.0.3
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - timm==0.9.12
      - torch==2.4.0+cu121
      - torchaudio==2.4.0+cu121
      - torchvision==0.19.0+cu121
      - tqdm==4.67.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
prefix: D:\complier\anaconda\envs\mpaper_10_21_py310
